import { useState } from "react";
import Head from "next/head";
import { TopNav, DataTable } from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [csvArray, setCsvArray] = useState([]);
  return (
    <div>
      <Head>
        <title>CSV Loader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <TopNav setCsvArray={setCsvArray} />
          <div className={styles.tableContainer}>
            <DataTable csvArray={csvArray} />
          </div>
        </div>
      </main>
    </div>
  );
}
